// ============================================================
// SISPENGAWAS MBG — Mock Data (centralized)
// ============================================================

export const sppgList = [
  { id: "SPPG-JB-001", nama: "Dapur Sehat Bandung Raya", provinsi: "Jawa Barat", kabupaten: "Kota Bandung", skorRisiko: 82, level: "Tinggi", slhs: false, ipal: false, sop: true, sopDiterapkan: false, lastInspeksi: "2025-12-10", biaya: 11800, volume: 1200, leadTime: 3.2 },
  { id: "SPPG-JB-002", nama: "Warung Gizi Mandiri Bogor", provinsi: "Jawa Barat", kabupaten: "Kota Bogor", skorRisiko: 71, level: "Tinggi", slhs: false, ipal: true, sop: false, sopDiterapkan: false, lastInspeksi: "2026-01-15", biaya: 10500, volume: 980, leadTime: 2.1 },
  { id: "SPPG-JT-001", nama: "Katering Nusantara Semarang", provinsi: "Jawa Tengah", kabupaten: "Kota Semarang", skorRisiko: 65, level: "Sedang", slhs: true, ipal: true, sop: true, sopDiterapkan: false, lastInspeksi: "2026-02-01", biaya: 10200, volume: 1500, leadTime: 1.8 },
  { id: "SPPG-JT-002", nama: "Dapur Berkah Solo", provinsi: "Jawa Tengah", kabupaten: "Kota Surakarta", skorRisiko: 44, level: "Sedang", slhs: false, ipal: true, sop: true, sopDiterapkan: true, lastInspeksi: "2026-01-20", biaya: 9900, volume: 870, leadTime: 1.5 },
  { id: "SPPG-JI-001", nama: "Mitra Gizi Surabaya Utara", provinsi: "Jawa Timur", kabupaten: "Kota Surabaya", skorRisiko: 78, level: "Tinggi", slhs: false, ipal: false, sop: false, sopDiterapkan: false, lastInspeksi: "2025-11-30", biaya: 12100, volume: 2100, leadTime: 4.0 },
  { id: "SPPG-JI-002", nama: "Katering Sehat Malang", provinsi: "Jawa Timur", kabupaten: "Kota Malang", skorRisiko: 38, level: "Rendah", slhs: true, ipal: true, sop: true, sopDiterapkan: true, lastInspeksi: "2026-02-10", biaya: 9800, volume: 760, leadTime: 1.2 },
  { id: "SPPG-DKI-001", nama: "Dapur Bergizi Jakarta Selatan", provinsi: "DKI Jakarta", kabupaten: "Jakarta Selatan", skorRisiko: 55, level: "Sedang", slhs: true, ipal: false, sop: true, sopDiterapkan: true, lastInspeksi: "2026-01-05", biaya: 10800, volume: 3200, leadTime: 2.3 },
  { id: "SPPG-DKI-002", nama: "Katering MBG Pulogadung", provinsi: "DKI Jakarta", kabupaten: "Jakarta Timur", skorRisiko: 88, level: "Tinggi", slhs: false, ipal: false, sop: false, sopDiterapkan: false, lastInspeksi: "2025-10-15", biaya: 13500, volume: 2800, leadTime: 5.1 },
  { id: "SPPG-BJR-001", nama: "Mitra Pangan Banjarmasin", provinsi: "Kalimantan Selatan", kabupaten: "Kota Banjarmasin", skorRisiko: 32, level: "Rendah", slhs: true, ipal: true, sop: true, sopDiterapkan: true, lastInspeksi: "2026-02-20", biaya: 9600, volume: 540, leadTime: 1.0 },
  { id: "SPPG-SLW-001", nama: "Dapur Sehat Makassar", provinsi: "Sulawesi Selatan", kabupaten: "Kota Makassar", skorRisiko: 61, level: "Sedang", slhs: false, ipal: true, sop: true, sopDiterapkan: false, lastInspeksi: "2025-12-28", biaya: 10400, volume: 1100, leadTime: 2.0 },
  { id: "SPPG-SUM-001", nama: "Katering Bergizi Medan", provinsi: "Sumatera Utara", kabupaten: "Kota Medan", skorRisiko: 73, level: "Tinggi", slhs: false, ipal: false, sop: true, sopDiterapkan: false, lastInspeksi: "2025-12-01", biaya: 11200, volume: 1800, leadTime: 3.5 },
  { id: "SPPG-RIU-001", nama: "Mitra Gizi Pekanbaru", provinsi: "Riau", kabupaten: "Kota Pekanbaru", skorRisiko: 29, level: "Rendah", slhs: true, ipal: true, sop: true, sopDiterapkan: true, lastInspeksi: "2026-02-15", biaya: 9700, volume: 620, leadTime: 1.3 },
  { id: "SPPG-JB-003", nama: "Dapur Nusantara Depok", provinsi: "Jawa Barat", kabupaten: "Kota Depok", skorRisiko: 67, level: "Sedang", slhs: false, ipal: true, sop: false, sopDiterapkan: false, lastInspeksi: "2026-01-28", biaya: 10700, volume: 1400, leadTime: 2.6 },
  { id: "SPPG-JT-003", nama: "Katering Berkah Yogyakarta", provinsi: "DI Yogyakarta", kabupaten: "Kota Yogyakarta", skorRisiko: 41, level: "Sedang", slhs: true, ipal: false, sop: true, sopDiterapkan: true, lastInspeksi: "2026-02-05", biaya: 9900, volume: 830, leadTime: 1.6 },
  { id: "SPPG-BTN-001", nama: "Mitra Pangan Serang", provinsi: "Banten", kabupaten: "Kota Serang", skorRisiko: 57, level: "Sedang", slhs: false, ipal: true, sop: true, sopDiterapkan: false, lastInspeksi: "2026-01-12", biaya: 10300, volume: 920, leadTime: 2.2 },
];

export const recentAlerts = [
  { sppgId: "SPPG-DKI-002", nama: "Katering MBG Pulogadung", lokasi: "Jakarta Timur", skorRisiko: 88, issue: "SLHS & IPAL tidak ada, biaya 35% di atas baseline", status: "Kritis" },
  { sppgId: "SPPG-JB-001", nama: "Dapur Sehat Bandung Raya", lokasi: "Kota Bandung", skorRisiko: 82, issue: "SLHS belum diperpanjang, anomali biaya terdeteksi", status: "Tinggi" },
  { sppgId: "SPPG-JI-001", nama: "Mitra Gizi Surabaya Utara", lokasi: "Kota Surabaya", skorRisiko: 78, issue: "Lead time distribusi melebihi 4 jam, dokumen tidak lengkap", status: "Tinggi" },
  { sppgId: "SPPG-SUM-001", nama: "Katering Bergizi Medan", lokasi: "Kota Medan", skorRisiko: 73, issue: "Foto bukti distribusi metadata tidak sesuai", status: "Tinggi" },
  { sppgId: "SPPG-JB-002", nama: "Warung Gizi Mandiri Bogor", lokasi: "Kota Bogor", skorRisiko: 71, issue: "SOP keamanan pangan belum ada", status: "Tinggi" },
];

export const provinsiRiskData = [
  { provinsi: "DKI Jakarta", tinggi: 312, sedang: 445, rendah: 198 },
  { provinsi: "Jawa Barat", tinggi: 287, sedang: 521, rendah: 412 },
  { provinsi: "Jawa Tengah", tinggi: 198, sedang: 387, rendah: 320 },
  { provinsi: "Jawa Timur", tinggi: 243, sedang: 412, rendah: 298 },
  { provinsi: "Banten", tinggi: 87, sedang: 143, rendah: 112 },
  { provinsi: "Sumatera Utara", tinggi: 123, sedang: 234, rendah: 187 },
  { provinsi: "Sulawesi Selatan", tinggi: 76, sedang: 198, rendah: 143 },
  { provinsi: "Kalimantan Selatan", tinggi: 45, sedang: 123, rendah: 98 },
  { provinsi: "Riau", tinggi: 54, sedang: 112, rendah: 87 },
  { provinsi: "DI Yogyakarta", tinggi: 87, sedang: 165, rendah: 134 },
];

export const complianceData = [
  { dokumen: "SLHS", compliant: 34, partial: 0, nonCompliant: 8549 },
  { dokumen: "IPAL Standar", compliant: 1069, partial: 312, nonCompliant: 131 },
  { dokumen: "SOP Punya", compliant: 413, partial: 0, nonCompliant: 966 },
  { dokumen: "SOP Diterapkan", compliant: 312, partial: 101, nonCompliant: 966 },
  { dokumen: "Sertif. Halal", compliant: 2341, partial: 0, nonCompliant: 6242 },
  { dokumen: "Izin Usaha", compliant: 7123, partial: 412, nonCompliant: 1048 },
];

export const biayaAnomalyData = [
  { bulan: "Apr '25", aktual: 9800, baseline: 10000 },
  { bulan: "Mei '25", aktual: 10100, baseline: 10000 },
  { bulan: "Jun '25", aktual: 10300, baseline: 10000 },
  { bulan: "Jul '25", aktual: 12400, baseline: 10000, anomaly: true },
  { bulan: "Ags '25", aktual: 10200, baseline: 10000 },
  { bulan: "Sep '25", aktual: 10000, baseline: 10000 },
  { bulan: "Okt '25", aktual: 9900, baseline: 10000 },
  { bulan: "Nov '25", aktual: 13100, baseline: 10000, anomaly: true },
  { bulan: "Des '25", aktual: 10400, baseline: 10000 },
  { bulan: "Jan '26", aktual: 10100, baseline: 10000 },
  { bulan: "Feb '26", aktual: 13500, baseline: 10000, anomaly: true },
  { bulan: "Mar '26", aktual: 10800, baseline: 10000 },
];

export const biayaAnomalyTable = [
  { sppgId: "SPPG-DKI-002", periode: "Feb 2026", aktual: 13500, baseline: 10000, deviasi: 35.0, zScore: 4.2, status: "Anomali" },
  { sppgId: "SPPG-JB-001", periode: "Nov 2025", aktual: 12800, baseline: 10000, deviasi: 28.0, zScore: 3.8, status: "Anomali" },
  { sppgId: "SPPG-JI-001", periode: "Jul 2025", aktual: 12100, baseline: 10000, deviasi: 21.0, zScore: 2.9, status: "Anomali" },
  { sppgId: "SPPG-SUM-001", periode: "Jan 2026", aktual: 11200, baseline: 10000, deviasi: 12.0, zScore: 1.8, status: "Perhatian" },
  { sppgId: "SPPG-JT-001", periode: "Feb 2026", aktual: 10800, baseline: 10000, deviasi: 8.0, zScore: 1.2, status: "Normal" },
];

export const volumeScatterData = [
  { dilaporkan: 1200, terverifikasi: 1180, sppg: "SPPG-JT-001" },
  { dilaporkan: 980, terverifikasi: 960, sppg: "SPPG-JB-002" },
  { dilaporkan: 2800, terverifikasi: 1950, sppg: "SPPG-DKI-002", anomaly: true },
  { dilaporkan: 1500, terverifikasi: 1480, sppg: "SPPG-JT-001" },
  { dilaporkan: 870, terverifikasi: 850, sppg: "SPPG-JT-002" },
  { dilaporkan: 2100, terverifikasi: 1420, sppg: "SPPG-JI-001", anomaly: true },
  { dilaporkan: 760, terverifikasi: 755, sppg: "SPPG-JI-002" },
  { dilaporkan: 3200, terverifikasi: 3150, sppg: "SPPG-DKI-001" },
  { dilaporkan: 540, terverifikasi: 538, sppg: "SPPG-BJR-001" },
  { dilaporkan: 1100, terverifikasi: 920, sppg: "SPPG-SLW-001", anomaly: true },
  { dilaporkan: 1800, terverifikasi: 1780, sppg: "SPPG-SUM-001" },
  { dilaporkan: 620, terverifikasi: 618, sppg: "SPPG-RIU-001" },
];

export const leadTimeData = [
  { sppg: "SPPG-DKI-002", rencana: 1.5, aktual: 5.1, deviasi: 240, risiko: "Tinggi" },
  { sppg: "SPPG-JI-001", rencana: 2.0, aktual: 4.0, deviasi: 100, risiko: "Tinggi" },
  { sppg: "SPPG-SUM-001", rencana: 2.0, aktual: 3.5, deviasi: 75, risiko: "Sedang" },
  { sppg: "SPPG-JB-001", rencana: 2.0, aktual: 3.2, deviasi: 60, risiko: "Sedang" },
  { sppg: "SPPG-JB-003", rencana: 2.0, aktual: 2.6, deviasi: 30, risiko: "Sedang" },
  { sppg: "SPPG-DKI-001", rencana: 2.0, aktual: 2.3, deviasi: 15, risiko: "Rendah" },
  { sppg: "SPPG-JT-001", rencana: 1.5, aktual: 1.8, deviasi: 20, risiko: "Rendah" },
];

export const nutrisiData = [
  { menu: "Menu A - Nasi + Ayam", sppg: "SPPG-DKI-002", kaloriRencana: 600, kaloriAktual: 487, proteinDev: -18.3, status: "Menyimpang" },
  { menu: "Menu B - Mie Goreng", sppg: "SPPG-JI-001", kaloriRencana: 580, kaloriAktual: 501, proteinDev: -12.1, status: "Perhatian" },
  { menu: "Menu C - Nasi + Ikan", sppg: "SPPG-JB-001", kaloriRencana: 620, kaloriAktual: 615, proteinDev: -2.1, status: "Normal" },
  { menu: "Menu D - Bubur Ayam", sppg: "SPPG-JT-001", kaloriRencana: 450, kaloriAktual: 448, proteinDev: 0.5, status: "Normal" },
  { menu: "Menu E - Nasi + Tempe", sppg: "SPPG-SUM-001", kaloriRencana: 560, kaloriAktual: 489, proteinDev: -9.8, status: "Perhatian" },
];

export const nutrisiBarData = [
  { kategori: "Protein", rencana: 30, aktual: 24.5 },
  { kategori: "Karbohidrat", rencana: 85, aktual: 82.3 },
  { kategori: "Lemak", rencana: 18, aktual: 17.8 },
  { kategori: "Kalori", rencana: 600, aktual: 548 },
];

export const correctiveActions = [
  { id: "CA-2026-001", sppg: "SPPG-DKI-002", temuan: "SLHS belum diperpanjang sejak 2024", kategori: "Kepatuhan Dokumen", assignee: "Insp. Rudi Hartono", deadline: "2026-04-01", progress: 20, status: "Dalam Proses", prioritas: "Tinggi" },
  { id: "CA-2026-002", sppg: "SPPG-JI-001", temuan: "Biaya per porsi melebihi threshold 21%", kategori: "Anomali Keuangan", assignee: "Insp. Sari Dewi", deadline: "2026-03-28", progress: 65, status: "Menunggu Verifikasi", prioritas: "Tinggi" },
  { id: "CA-2026-003", sppg: "SPPG-JB-001", temuan: "Bukti foto distribusi metadata tidak sesuai", kategori: "Bukti Lapangan", assignee: "Insp. Agus Salim", deadline: "2026-04-10", progress: 40, status: "Dalam Proses", prioritas: "Tinggi" },
  { id: "CA-2026-004", sppg: "SPPG-SUM-001", temuan: "Kandungan protein di bawah standar 18%", kategori: "Penyimpangan Gizi", assignee: "Insp. Maya Putri", deadline: "2026-04-05", progress: 10, status: "Temuan Baru", prioritas: "Tinggi" },
  { id: "CA-2026-005", sppg: "SPPG-JI-001", temuan: "IPAL tidak memenuhi standar Kemenkes", kategori: "Kepatuhan Dokumen", assignee: "Insp. Budi Santoso", deadline: "2026-05-01", progress: 80, status: "Menunggu Verifikasi", prioritas: "Tinggi" },
  { id: "CA-2026-006", sppg: "SPPG-JT-001", temuan: "SOP keamanan pangan belum diterapkan", kategori: "Kepatuhan SOP", assignee: "Insp. Dewi Rahayu", deadline: "2026-04-15", progress: 55, status: "Dalam Proses", prioritas: "Sedang" },
  { id: "CA-2026-007", sppg: "SPPG-DKI-001", temuan: "Lead time distribusi melebihi 2 jam dari rencana", kategori: "Anomali Distribusi", assignee: "Insp. Eko Prasetyo", deadline: "2026-03-30", progress: 90, status: "Menunggu Verifikasi", prioritas: "Sedang" },
  { id: "CA-2026-008", sppg: "SPPG-JB-003", temuan: "Sertifikasi halal kadaluarsa", kategori: "Kepatuhan Dokumen", assignee: "Insp. Fitri Handayani", deadline: "2026-04-20", progress: 30, status: "Dalam Proses", prioritas: "Sedang" },
  { id: "CA-2026-009", sppg: "SPPG-BTN-001", temuan: "Volume terdistribusi tidak sesuai laporan 15%", kategori: "Anomali Volume", assignee: "Insp. Galih Permana", deadline: "2026-04-08", progress: 5, status: "Temuan Baru", prioritas: "Sedang" },
  { id: "CA-2026-010", sppg: "SPPG-JB-002", temuan: "SOP keamanan pangan belum ada", kategori: "Kepatuhan SOP", assignee: "Insp. Hana Kusuma", deadline: "2026-05-15", progress: 0, status: "Temuan Baru", prioritas: "Sedang" },
  { id: "CA-2025-087", sppg: "SPPG-JI-002", temuan: "Pelatihan higienis dapur belum terlaksana", kategori: "Kapasitas SDM", assignee: "Insp. Irfan Nugraha", deadline: "2026-01-31", progress: 100, status: "Selesai", prioritas: "Rendah" },
  { id: "CA-2025-088", sppg: "SPPG-BJR-001", temuan: "Dokumen izin usaha perlu diperbarui", kategori: "Kepatuhan Dokumen", assignee: "Insp. Joko Widodo", deadline: "2026-02-15", progress: 100, status: "Selesai", prioritas: "Rendah" },
];

export const auditTrailData = [
  { timestamp: "2026-03-26 08:42:11", aktor: "System", aksi: "Risk score recalculated — SPPG-DKI-002 naik ke 88", sppg: "SPPG-DKI-002", modul: "Risk Scoring", hash: "a3f8b2c1d4e5f6a7", status: "Success" },
  { timestamp: "2026-03-26 08:30:05", aktor: "Insp. Rudi Hartono", aksi: "Corrective action CA-2026-001 diperbarui — progress 20%", sppg: "SPPG-DKI-002", modul: "Corrective Action", hash: "b4c9d3e2f1a0b5c6", status: "Success" },
  { timestamp: "2026-03-26 07:15:33", aktor: "System", aksi: "Anomaly flagged — biaya per porsi SPPG-JB-001 naik 28%", sppg: "SPPG-JB-001", modul: "Anomaly Detection", hash: "c5d0e4f3a2b1c7d8", status: "Alert" },
  { timestamp: "2026-03-25 16:22:47", aktor: "Insp. Sari Dewi", aksi: "Inspector field visit logged — SPPG-JI-001", sppg: "SPPG-JI-001", modul: "Corrective Action", hash: "d6e1f5a4b3c2d9e0", status: "Success" },
  { timestamp: "2026-03-25 14:11:20", aktor: "Admin BGN", aksi: "Document compliance updated — SPPG-JT-001 SLHS verified", sppg: "SPPG-JT-001", modul: "Compliance Engine", hash: "e7f2a6b5c4d3e0f1", status: "Success" },
  { timestamp: "2026-03-25 11:45:02", aktor: "System", aksi: "Risk score recalculated — SPPG-SUM-001 turun ke 73", sppg: "SPPG-SUM-001", modul: "Risk Scoring", hash: "f8a3b7c6d5e4f1a2", status: "Success" },
  { timestamp: "2026-03-25 09:30:18", aktor: "Insp. Maya Putri", aksi: "Corrective action CA-2026-004 dibuat — penyimpangan gizi", sppg: "SPPG-SUM-001", modul: "Corrective Action", hash: "a9b4c8d7e6f5a2b3", status: "Success" },
  { timestamp: "2026-03-24 17:05:44", aktor: "System", aksi: "Anomaly flagged — volume SPPG-DKI-002 selisih 850 porsi", sppg: "SPPG-DKI-002", modul: "Anomaly Detection", hash: "b0c5d9e8f7a6b3c4", status: "Alert" },
  { timestamp: "2026-03-24 15:22:31", aktor: "Admin BGN", aksi: "Corrective action assigned — CA-2026-001 ke Insp. Rudi Hartono", sppg: "SPPG-DKI-002", modul: "Corrective Action", hash: "c1d6e0f9a8b7c4d5", status: "Success" },
  { timestamp: "2026-03-24 13:00:00", aktor: "System", aksi: "Scheduled compliance check — 25.020 SPPG diproses", sppg: "ALL", modul: "Compliance Engine", hash: "d2e7f1a0b9c8d5e6", status: "Success" },
  { timestamp: "2026-03-24 10:15:22", aktor: "Insp. Agus Salim", aksi: "Bukti foto distribusi diverifikasi — metadata tidak sesuai", sppg: "SPPG-JB-001", modul: "Anomaly Detection", hash: "e3f8a2b1c0d9e6f7", status: "Alert" },
  { timestamp: "2026-03-23 16:44:09", aktor: "System", aksi: "Lead time anomaly detected — SPPG-JI-001 rute Surabaya", sppg: "SPPG-JI-001", modul: "Anomaly Detection", hash: "f4a9b3c2d1e0f7a8", status: "Alert" },
  { timestamp: "2026-03-23 14:30:55", aktor: "Admin BGN", aksi: "Evidence pack generated — periode Q1 2026 SPPG-DKI-002", sppg: "SPPG-DKI-002", modul: "Audit Evidence", hash: "a5b0c4d3e2f1a8b9", status: "Success" },
  { timestamp: "2026-03-23 11:20:33", aktor: "Insp. Budi Santoso", aksi: "IPAL inspection completed — tidak memenuhi standar Kemenkes", sppg: "SPPG-JI-001", modul: "Compliance Engine", hash: "b6c1d5e4f3a2b9c0", status: "Alert" },
  { timestamp: "2026-03-22 09:00:00", aktor: "System", aksi: "Weekly risk scoring run — 25.020 SPPG diperbarui", sppg: "ALL", modul: "Risk Scoring", hash: "c7d2e6f5a4b3c0d1", status: "Success" },
  { timestamp: "2026-03-21 16:55:12", aktor: "Insp. Dewi Rahayu", aksi: "SOP verification visit — SPPG-JT-001 partial compliance", sppg: "SPPG-JT-001", modul: "Compliance Engine", hash: "d8e3f7a6b5c4d1e2", status: "Success" },
  { timestamp: "2026-03-21 14:12:44", aktor: "Admin BGN", aksi: "Nutrition test result uploaded — Menu A SPPG-DKI-002", sppg: "SPPG-DKI-002", modul: "Anomaly Detection", hash: "e9f4a8b7c6d5e2f3", status: "Alert" },
  { timestamp: "2026-03-20 10:30:00", aktor: "System", aksi: "Document expiry alert — SLHS SPPG-JB-001 jatuh tempo", sppg: "SPPG-JB-001", modul: "Compliance Engine", hash: "f0a5b9c8d7e6f3a4", status: "Alert" },
  { timestamp: "2026-03-20 08:45:17", aktor: "Insp. Eko Prasetyo", aksi: "Corrective action CA-2026-007 progress diperbarui 90%", sppg: "SPPG-DKI-001", modul: "Corrective Action", hash: "a1b6c0d9e8f7a4b5", status: "Success" },
  { timestamp: "2026-03-19 15:22:08", aktor: "System", aksi: "Biaya anomaly spike detected — SPPG-DKI-002 Feb 2026", sppg: "SPPG-DKI-002", modul: "Anomaly Detection", hash: "b2c7d1e0f9a8b5c6", status: "Alert" },
];

export const auditEvidence = [
  {
    id: "EV-2026-001",
    sppg: "SPPG-DKI-002",
    type: "Foto Bukti",
    filename: "distribusi_25maret_pukul0730.jpg",
    inspector: "Insp. Rudi Hartono",
    uploadDate: "2026-03-26",
    uploadTime: "08:15",
    location: "Jakarta Timur - Rrt. Kayu Putih",
    fileSize: 3.2,
    relatedFinding: "CA-2026-001",
    description: "Bukti distribusi pagi ke sekolah",
    status: "Verified" as const,
    notes: "Metadata sesuai, timestamp akurat",
  },
  {
    id: "EV-2026-002",
    sppg: "SPPG-JI-001",
    type: "Lab Result",
    filename: "analisis_gizi_20maret.pdf",
    inspector: "Lab BGN - Dr. Siti",
    uploadDate: "2026-03-24",
    uploadTime: "14:30",
    location: "Lab Gizi Pusat BGN",
    fileSize: 1.8,
    relatedFinding: "CA-2026-004",
    description: "Hasil uji lab kandungan gizi Menu B - protein 24.5g (target 30g)",
    status: "Verified" as const,
    notes: "Penyimpangan protein terdeteksi",
  },
  {
    id: "EV-2026-003",
    sppg: "SPPG-JB-001",
    type: "Dokumentasi Inspeksi",
    filename: "checklist_inspeksi_ssop_21mar.docx",
    inspector: "Insp. Agus Salim",
    uploadDate: "2026-03-21",
    uploadTime: "16:45",
    location: "Dapur Sehat Bandung Raya",
    fileSize: 0.4,
    relatedFinding: "CA-2026-003",
    description: "Checklist SSOP - foto metadata tidak sesuai datetime",
    status: "Flagged" as const,
    notes: "Metadata foto tidak konsisten dengan tanggal inspeksi",
  },
  {
    id: "EV-2026-004",
    sppg: "SPPG-SUM-001",
    type: "Foto Bukti",
    filename: "kondisi_peralatan_kitchen.jpg",
    inspector: "Insp. Maya Putri",
    uploadDate: "2026-03-22",
    uploadTime: "09:20",
    location: "Katering Bergizi Medan",
    fileSize: 2.9,
    relatedFinding: null,
    description: "Kondisi peralatan dapur - masih layak pakai",
    status: "Verified" as const,
    notes: "Peralatan sesuai standar higienis",
  },
  {
    id: "EV-2026-005",
    sppg: "SPPG-DKI-001",
    type: "Dokumentasi Inspeksi",
    filename: "sertifikat_slhs_dki001_nov2024.pdf",
    inspector: "Admin BGN",
    uploadDate: "2026-03-20",
    uploadTime: "11:00",
    location: "Sistem Dokumen Digital",
    fileSize: 0.8,
    relatedFinding: null,
    description: "Sertifikat SLHS terbaru - berlaku sampai November 2026",
    status: "Verified" as const,
    notes: "Dokumen valid dan terupdate",
  },
  {
    id: "EV-2026-006",
    sppg: "SPPG-JI-001",
    type: "Foto Bukti",
    filename: "ipal_kondisi_tidak_standar.jpg",
    inspector: "Insp. Budi Santoso",
    uploadDate: "2026-03-23",
    uploadTime: "13:15",
    location: "Mitra Gizi Surabaya Utara - Area IPAL",
    fileSize: 2.5,
    relatedFinding: "CA-2026-005",
    description: "Foto IPAL - tidak memenuhi standar Kemenkes untuk kapasitas limbah",
    status: "Flagged" as const,
    notes: "IPAL perlu upgrade - rekomendasi tindakan perbaikan",
  },
  {
    id: "EV-2026-007",
    sppg: "SPPG-JT-001",
    type: "Foto Bukti",
    filename: "sop_keamanan_pangan_wall_poster.jpg",
    inspector: "Insp. Dewi Rahayu",
    uploadDate: "2026-03-21",
    uploadTime: "10:30",
    location: "Dapur Berkah Solo - Area Produksi",
    fileSize: 1.6,
    relatedFinding: null,
    description: "Poster SOP keamanan pangan tertempel di area produksi",
    status: "Verified" as const,
    notes: "SOP visible dan mudah dibaca oleh semua karyawan",
  },
  {
    id: "EV-2026-008",
    sppg: "SPPG-DKI-002",
    type: "Foto Bukti",
    filename: "biaya_perhitungan_sheet_maret.xlsx",
    inspector: "Insp. Rudi Hartono",
    uploadDate: "2026-03-25",
    uploadTime: "15:20",
    location: "Kantor Katering MBG Pulogadung",
    fileSize: 0.3,
    relatedFinding: "CA-2026-002",
    description: "Breakdown harga per porsi Maret 2026 - Rp 13.500/porsi (+35% baseline)",
    status: "Verified" as const,
    notes: "Anomali biaya terverifikasi - perlu penjelasan manajemen",
  },
  {
    id: "EV-2026-009",
    sppg: "SPPG-JB-002",
    type: "Dokumentasi Inspeksi",
    filename: "training_log_keamanan_pangan.pdf",
    inspector: "Insp. Hana Kusuma",
    uploadDate: "2026-03-20",
    uploadTime: "14:45",
    location: "Warung Gizi Mandiri Bogor - Arsip Pelatihan",
    fileSize: 1.2,
    relatedFinding: "CA-2026-010",
    description: "Log pelatihan keamanan pangan karyawan - kosong sejak 2024",
    status: "Flagged" as const,
    notes: "Tidak ada bukti pelatihan rutin - perlu pelaksanaan segera",
  },
  {
    id: "EV-2026-010",
    sppg: "SPPG-BJR-001",
    type: "Lab Result",
    filename: "hasil_uji_lab_februari_2026.pdf",
    inspector: "Lab BGN - Dr. Karyo",
    uploadDate: "2026-03-19",
    uploadTime: "09:00",
    location: "Lab Mikrobiologi BGN",
    fileSize: 0.6,
    relatedFinding: null,
    description: "Uji lab lengkap - protein 28g, kalori 598, semua parameter normal",
    status: "Verified" as const,
    notes: "Hasil lab menunjukkan kepatuhan gizi sempurna",
  },
];